project:
  type: website

website:
  title: "Final Project"
  navbar:
    background: blue
    left:
      - href: about.qmd
        text: About
      - href: model.qmd
        text: Model
      - href: eda.qmd
        text: EDA
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

